### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by KBMatveev** [omaralbeik/SwifterSwift#22]
Then use  - `let someString = String(" 123 ").trimmed`
have error - `Value of type "String?" has no member 'trimmed'`

Why?

**Comment by omaralbeik** [comment]
@KBMatveev did you add "import SwifterSwift" to the top of the file?

**Comment by KBMatveev** [comment]
No. But `let today = Date().beginning(of: .day)! ` work without import. And `startDate = today.adding(.year, value: -1)` too

**Comment by omaralbeik** [comment]
@KBMatveev some time some extensions don't work without import, please import SwifterSwift at every file you want to use it in, and let me know if you still have the problem

**Comment by KBMatveev** [comment]
`import SwifterSwift - No Such module 'SwifterSwift'`
I add directory 'Extensions' manually.

"Manually
Add the extensions folder to your Xcode project to use all extensions, or a specific extension."

**Comment by omaralbeik** [comment]
@KBMatveev and if you didn't clean and rebuild the project from the "Product" menu after installing the pod, it's also preferred to do that

**Comment by omaralbeik** [comment]
@KBMatveev Then please make sure to check "Copy items if needed" and "Add to targets" checkboxes when adding the files to your xcode project

**Comment by KBMatveev** [comment]
![2016-12-12 10 58 42](https://cloud.githubusercontent.com/assets/19492758/21091862/010f0380-c05a-11e6-8261-30bbecbdb675.png)

Not work. In edit mode XCode found and show trimmed extension

![2016-12-12 11 00 49](https://cloud.githubusercontent.com/assets/19492758/21091907/46024664-c05a-11e6-9b62-fb537fa6a0c9.png)

When build - error 

![2016-12-12 11 01 36](https://cloud.githubusercontent.com/assets/19492758/21091934/62be2908-c05a-11e6-9727-21aa9e536cdf.png)

**Comment by omaralbeik** [comment]
@KBMatveev I think the code should be
`let someString = String(" 123 ")?.trimmed`
trimmed is a **String** extension not a **String?** extension
Please try adding ? and let me know if this fixes the problem

**Comment by KBMatveev** [comment]
Not work
![2016-12-12 11 05 45](https://cloud.githubusercontent.com/assets/19492758/21092028/05a214f4-c05b-11e6-9a41-1f8abdb5a594.png)

**Comment by omaralbeik** [comment]
@KBMatveev 🤔, are you using xcode 8 with swift 3?

**Comment by KBMatveev** [comment]
Of course. :-)
![2016-12-12 11 16 27](https://cloud.githubusercontent.com/assets/19492758/21092286/75266e28-c05c-11e6-8133-fc2bd3d44a81.png)

**Comment by KBMatveev** [comment]
DateExtensions work good, UITableViewExtensions too, trouble only with SringExtensions

**Comment by omaralbeik** [comment]
@KBMatveev Then I assume the StringExtensions.swift file is not added to the target, could you please delete it, and re-add it to project while making sure to add it to target and copy if needed <img width="1127" alt="viewcontroller_swift" src="https://cloud.githubusercontent.com/assets/8127757/21092373/a52331ea-c054-11e6-9543-2e8301a67419.png">

**Comment by KBMatveev** [comment]
I add the entire directory "Extensions", so it is unlikely that some files were added as DateExtensions, and some do not. But it's good. Will make again.
![2016-12-12 11 27 15](https://cloud.githubusercontent.com/assets/19492758/21092524/fcecd454-c05d-11e6-81ce-64a67a74341e.png)
![2016-12-12 11 28 58](https://cloud.githubusercontent.com/assets/19492758/21092560/36cf2f96-c05e-11e6-8222-8b09ad2e0e5f.png)
![2016-12-12 11 30 03](https://cloud.githubusercontent.com/assets/19492758/21092589/5bebbed4-c05e-11e6-8a61-e30ba53fbbca.png)

**Comment by KBMatveev** [comment]
![2016-12-12 11 32 35](https://cloud.githubusercontent.com/assets/19492758/21092650/b90a481a-c05e-11e6-9f24-ece1ce58c094.png)

**Comment by omaralbeik** [comment]
@KBMatveev weird!! , the StringExtensions.swift file follows the same structure of all other extensions files, and it is public

is this code working for you?
`let someString = String(" 123 ")!.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines)`

**Comment by omaralbeik** [comment]
@KBMatveev I'm trying to understand what is causing the problem in your end, I've tested this with multiple projects, as I see in the first picture you sent the autocompletion is completing the trimmed for you, which means xcode can see the file!
do you have another string method or property called trimmed somewhere else in your project?

**Comment by KBMatveev** [comment]
Yes. Look second string. 
![2016-12-12 11 38 31](https://cloud.githubusercontent.com/assets/19492758/21092839/bf708e20-c05f-11e6-8a61-3f839af2ad5b.png)
Had to pull it out Stringextension. Works. 
Must be `let rt = region.trimmed`

**Comment by omaralbeik** [comment]
@KBMatveev is the problem solved ?

**Comment by KBMatveev** [comment]
> do you have another string method or property called trimmed somewhere else in your project?

I have not tried everything. Reverse() does not work.
![2016-12-12 11 43 41](https://cloud.githubusercontent.com/assets/19492758/21092972/5cd862f0-c060-11e6-87d6-8992b39fd565.png)
![2016-12-12 11 44 06](https://cloud.githubusercontent.com/assets/19492758/21092961/51d11514-c060-11e6-96b6-d8fa3d112871.png)

**Comment by omaralbeik** [comment]
@KBMatveev I don't know what is happening in your end, everything is working correctly for me, I'd be glad to check it myself with teamviewer if you want

**Comment by KBMatveev** [comment]
> is the problem solved ?

I replaced trimmed on trimmingCharacters. It worked, but hardly a solution to the problem.

You want to connect via TeamViewer?

**Comment by omaralbeik** [comment]
@KBMatveev I'll try to check what is causing the problem if you want via teamviewer

**Comment by KBMatveev** [comment]
Send password via eMail

**Comment by omaralbeik** [comment]
@KBMatveev Glad your problem is fixed, I think the problem is when adding files from the file menu, they didn't get added to target for some reason, dragging the files to the project, always shows you the confirmation menu, where you can double check that files are added to your target
