### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by TofPlay** [omaralbeik/SwifterSwift#23]
Hi,
For iOS projets it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://realm.io/news/swift-dependency-management-with-carthage/)
- [Carthage Tutorial: Getting Started](https://www.raywenderlich.com/109330/carthage-tutorial-getting-started)
- [Making Carthage-compatible Frameworks with Swift](http://blog.mat.tc/how-to-make-a-carthage-compatible-framework/)
- [Creating Cross-Platform Swift Frameworks for iOS, watchOS, and tvOS via Carthage and CocoaPods](http://basememara.com/creating-cross-platform-swift-frameworks-ios-watchos-tvos-via-carthage-cocoapods/) 👍

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by omaralbeik** [comment]
@TofPlay Sure, Carthage will be added in the next release,
I'll let you know when it's added here
Thank you!

**Comment by omaralbeik** [comment]
@TofPlay Carthage support added!
Thank you for your feedback.
