### ISSUE TITLE
About the "Coding Style"

### ISSUE THREAD

**Issue by wudijimao** [omaralbeik/SwifterSwift#34]
As I know, In Objective-C, Extension functions often write with a fix prefix.  like "sd_xxx".   I think swift extension should be do it as the same to forbidden conflict to other's extension?

**Comment by omaralbeik** [comment]
@wudijimao Thank you for your comment, We decided to make all extensions in SwifterSwift look like native functions as the [Swift API Design Guidelines](https://developer.apple.com/videos/play/wwdc2016/403/) recommends. (Thats what makes SwifterSwift great actually).
All properties and functions coming from SwifterSwift have the **SwifterSwift:** prefix in their description, so you know where they are coming from and disable a specific function or preperty incase of a conflict with another extension.
Adding a fixed prefix to function names is as you said Obj-C way, and the library is **Swifter**Swift, which means making swift more swifty! ;)
