### ISSUE TITLE
UIView fadeIn fadeOut

### ISSUE THREAD

**Issue by bastianschilbe** [omaralbeik/SwifterSwift#46]
Seems like fadeIn is setting the alpha to 0 and fadeOut is setting the alpha to 1. Is that correct?

**Comment by pvtmert** [comment]
alpha = 1 means it is transparent (FFxxxxxx) and no alpha (00xxxxxx) means it is opaque, it is intended functionality and general logic

**Comment by bastianschilbe** [comment]
https://developer.apple.com/reference/uikit/uiview/1622417-alpha

Sorry but the docs say it's the other way around.

**Comment by pvtmert** [comment]
oops then fix is on the way :)

**Comment by bastianschilbe** [comment]
Cool 8)

**Comment by omaralbeik** [comment]
@bastianschilbe fixed in #48, Thank you for reporting.

**Comment by wdcurry** [comment]
I tweaked my copy to 
`public func fadeOut(toAlpha: CGFloat = 0, duration: TimeInterval = 1, completion: ((Bool) -> Void)? = nil)` to give me better control, as the black was too much, but the functionality is sweet. So a popOver can now easily blur out the background a bit.
