### ISSUE TITLE
UIView rotate(toAngle

### ISSUE THREAD

**Issue by bastianschilbe** [omaralbeik/SwifterSwift#47]
This method will reset all other transformations applied to the view. UIView rotate(byAngle behaves differently

**Comment by pvtmert** [comment]
looks like [UIViewExtensions.swift](../blob/master/SwifterSwift/SwifterSwift/Extensions/UI/UIViewExtensions.swift) problem with override or animation stuff at [line 316](../blob/master/SwifterSwift/SwifterSwift/Extensions/UI/UIViewExtensions.swift#L316) and [line 336](../blob/master/SwifterSwift/SwifterSwift/Extensions/UI/UIViewExtensions.swift#L336)

**Comment by omaralbeik** [comment]
@bastianschilbe fixed in #48, Thank you for reporting.
