### ISSUE TITLE
Unable to find SwifterSwift

### ISSUE THREAD

**Issue by lenmoyouziJiangjun** [omaralbeik/SwifterSwift#49]
pod search SwifterSwift
[!] Unable to find a pod with name, author, summary, or description matching `SwifterSwift`

**Comment by omaralbeik** [comment]
@lenmoyouziJiangjun 
https://cocoapods.org/pods/SwifterSwift

<img width="729" alt="terminal" src="https://cloud.githubusercontent.com/assets/8127757/21254322/2f7bbfc2-c36d-11e6-952d-ea11ceeb8c47.png">
