### ISSUE TITLE
Inconsistent naming...

### ISSUE THREAD

**Issue by rpural** [omaralbeik/SwifterSwift#51]
Given the code:

	public var nearestHourQuarter: Date {
...
	public var nearestHalfHour: Date {

Shouldn't the first function be named "nearestQuarterHour", to match nearestHalfHour? Truthfully, when I was reading the code, I thought the function was named incorrectly even before I got to the second function. It just seems like it would be better to be consistent.

**Comment by omaralbeik** [comment]
@rpural I agree with you!
Will be updated in the next release

**Comment by omaralbeik** [comment]
Fixed in #54
