### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by pieterclaerhout** [omaralbeik/SwifterSwift#56]
It would be nice if you could update the podspec to allow usage of this in a tvOS project as well.

Thanks,

pieter

**Comment by omaralbeik** [comment]
@pieterclaerhout I think adding tvOS is not only updating the podspec, we have to test each extension in a tvOS target to make sure it works.
I'm working to bring macOS and tvOS support in version 2, but due  to my limited time and many projects nowadays this might take some time.
Please let me know if you are interested in helping on this

Thanks.

**Comment by omaralbeik** [comment]
Released version 1.4.5 with tvOS support, thanks to @pawurb.
