### ISSUE TITLE
UITableView .indexPathForLastRow is wrong

### ISSUE THREAD

**Issue by muescha** [omaralbeik/SwifterSwift#74]
https://github.com/omaralbeik/SwifterSwift/blob/development/Source/Extensions/UI/UITableViewExtensions.swift#L16

current implementation is wrong:
```
	public var indexPathForLastRow: IndexPath? {
		guard numberOfRows > 0 else {
			return nil
		}
		return IndexPath(row: numberOfRows - 1, section: lastSection)
	}
```
 
it should be:
```
     return IndexPath(row: indexPathForLastRow(in: lastSection), section: lastSection)
```

**Comment by omaralbeik** [comment]
```swift
return IndexPath(row: indexPathForLastRow(in: lastSection), section: lastSection)
```
@muescha True, however the above code is a bit repetitive and didn't work because an optional IndexPath being passed method instead of row

I refactored the code to:
```swift
public var indexPathForLastRow: IndexPath? {
    return indexPathForLastRow(inSection: lastSection)
}
```

Will change it in the next release, thank you!

**Comment by muescha** [comment]
yes - that is much shorter :)
