### ISSUE TITLE
naming is wrong: indexPathForLastRow(in section: Int)

### ISSUE THREAD

**Issue by muescha** [omaralbeik/SwifterSwift#75]
https://github.com/omaralbeik/SwifterSwift/blob/development/Source/Extensions/UI/UITableViewExtensions.swift#L49

naming should be equal to other `inSection` parameter namings

this:
```
public func indexPathForLastRow(in section: Int) -> IndexPath? {
```

should be:
```
public func indexPathForLastRow(inSection section: Int) -> IndexPath? {
```

**Comment by omaralbeik** [comment]
@muescha Updated names in all UITableViewExtensions and UICollectionViewExtensions methods. will merge changes into master in the next release. 
Thank you!
