### ISSUE TITLE
naming is wrong in indexPathForLastItem(in section: Int)

### ISSUE THREAD

**Issue by muescha** [omaralbeik/SwifterSwift#77]
https://github.com/omaralbeik/SwifterSwift/blob/development/Source/Extensions/UI/UICollectionViewExtensions.swift#L49

the naming should be equal as other `inSection` parameter naming:

```
	public func indexPathForLastItem(in section: Int) -> IndexPath? {
```

should be
```
	public func indexPathForLastItem(inSection section: Int) -> IndexPath? {
```

**Comment by omaralbeik** [comment]
@muescha Updated names in all UITableViewExtensions and UICollectionViewExtensions methods. will merge changes into master in the next release. 
Thank you!
